const tintColorLight = '#2563EB'; // Primary Light - matching web version
const tintColorDark = '#3B82F6'; // Primary Dark - matching web version

export const Colors = {
  light: {
    text: '#29333d',
    background: '#eafafb',
    tint: tintColorLight,
    icon: '#687076',
    tabIconDefault: '#687076',
    tabIconSelected: tintColorLight,
    card: '#ffffff',
    cardForeground: '#29333d',
    border: '#dae6e7',
    input: '#dae6e7',
    primary: tintColorLight,
    primaryForeground: '#ffffff',
    secondary: '#d9f2f5',
    secondaryForeground: '#29333d',
    destructive: '#ef4444',
    destructiveForeground: '#ffffff',
    muted: '#ebf5f6',
    mutedForeground: '#64748b',
    accent: '#82c982',
    pomodoroFocus: '#f5a61a',
    success: '#22c55e',
    warning: '#f59e0b',
    error: '#ef4444',
    info: '#3b82f6',
    placeholder: '#94a3b8',
  },
  dark: {
    text: '#eafafb',
    background: '#0f131a',
    tint: tintColorDark,
    icon: '#9BA1A6',
    tabIconDefault: '#9BA1A6',
    tabIconSelected: tintColorDark,
    card: '#151a23',
    cardForeground: '#eafafb',
    border: '#252d36',
    input: '#252d36',
    primary: tintColorDark,
    primaryForeground: '#ffffff',
    secondary: '#1f262e',
    secondaryForeground: '#eafafb',
    destructive: '#ef4444', // Kept same for visibility
    destructiveForeground: '#ffffff',
    muted: '#1f262e',
    mutedForeground: '#94a3b8',
    accent: '#82c982',
    pomodoroFocus: '#f5a61a',
    success: '#22c55e',
    warning: '#f59e0b',
    error: '#ef4444',
    info: '#3b82f6',
    placeholder: '#64748b',
  },
};